### ISSUE TITLE
Text::FormatTable fuzzes around with my data

### ISSUE THREAD

**Issue by mlawren** [treyharris/Text-FormatTable#2]
Text::FormatTable strips leading (and possibly tailing) whitespace characters. Also (probably related) it eliminates rows that contain only whitespace. This means that I cannot output tables that are an accurate representation of my data, nor can I nest one table inside another.

I presume that this "cleaning up" was meant as a feature for someone, but unfortunately that is not the case for me.

Given that it has been a long-standing behaviour, and the lack of tickets against this module, I presume it unlikely that you would accept patches that change this? Just though I would ask, before I fork it, under some other name of course.

**Comment by treyharris** [comment]
Hi there, not sure why you think I wouldn't accept a patch; so long as you add test cases, of course I will. The whitespace-stripping was just an existing behavior I preserved when I took over the module. If you could make it configurable, since I presume someone had a need for this stripping to have put it in, so much the better.
